/**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.eibus.applicationconnector.sap.exception;

import com.eibus.localization.message.Message;
import com.eibus.localization.message.MessageSet;

/**
 * This code is generated by running com.cordys.coe.cep.core.utils.CoEMessageGenerator.
 */

public class SAPConfigurationExceptionMessages
{ 

	public static final MessageSet MESSAGE_SET = MessageSet.getMessageSet("com.eibus.applicationconnector.sap.exception.SAPConfigurationExceptionMessages");

	/** Could not find tag {0} in the configuration XML */
	public static final Message ERR_COULD_NOT_FIND_TAG = MESSAGE_SET.getMessage("ErrCouldNotFindTag");

	/** The tag {0} has no value even though it's mandatory. */
	public static final Message ERR_TAG_HAS_NO_VALUE = MESSAGE_SET.getMessage("ErrTagHasNoValue");

	/** Either jco or bc tag must be present */
	public static final Message ERR_UNKNOWN_MIDDLEWARE = MESSAGE_SET.getMessage("ErrUnknownMiddleware");

	/** Invalid URL for invoking {0} */
	public static final Message ERR_INVALID_URL = MESSAGE_SET.getMessage("ErrInvalidUrl");

	/** Missing bapi data */
	public static final Message MISSING_BAPI_DATA = MESSAGE_SET.getMessage("MissingBapiData");

	/** Missing rfc data */
	public static final Message MISSING_RFC_DATA = MESSAGE_SET.getMessage("MissingRfcData");


}