
  CREATE TABLE "IDOCTABLE" 
   (	"DIRECTION" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"TID" VARCHAR2(24 BYTE) NOT NULL ENABLE, 
	"IDOCNUM" VARCHAR2(24 BYTE) NOT NULL ENABLE, 
	"CREATIONDATE" DATE, 
	"MESTYPE" VARCHAR2(24 BYTE) NOT NULL ENABLE, 
	"CIMTYPE" VARCHAR2(24 BYTE), 
	"SENDERLS" VARCHAR2(10 BYTE), 
	"RECEIVERLS" VARCHAR2(10 BYTE), 
	"LOCALSTATUS" VARCHAR2(24 BYTE) NOT NULL ENABLE, 
	"ERRORTEXT" VARCHAR2(16 BYTE), 
	"TARGETSYSTEM" VARCHAR2(24 BYTE), 
	"DESTINATIONSTATUS" VARCHAR2(2 BYTE), 
	"CONTROLRECORD" CLOB NOT NULL ENABLE, 
	"DATARECORD" CLOB NOT NULL ENABLE, 
	"IDOCTYPE" VARCHAR2(100 BYTE), 
	"SOAPNODEDN" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "IDOCTABLE_PK" PRIMARY KEY ("IDOCNUM", "SOAPNODEDN")  
   );