/**
 * Copyright 2005 Cordys R&D B.V. 
 * 
 * This file is part of the Cordys SAP Connector. 
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 package com.eibus.applicationconnector.sap;

import com.eibus.localization.message.Message;
import com.eibus.localization.message.MessageSet;

/**
 * This code is generated by running com.cordys.coe.cep.core.utils.CoEMessageGenerator.
 */

public class Messages
{ 

	public static final MessageSet MESSAGE_SET = MessageSet.getMessageSet("com.eibus.applicationconnector.sap.Messages");

	/** Parameter name is empty in the RFC Interface. */
	public static final Message WRN_PARAMETER_NAME_EMPTY = MESSAGE_SET.getMessage("WRN_PARAMETER_NAME_EMPTY");

	/** IDOC Server exception occurred: {0} */
	public static final Message ERR_IDOC_SERVER = MESSAGE_SET.getMessage("ERR_IDOC_SERVER");

	/** A SOAPFault occurred while checking for tid in the database: {0} */
	public static final Message ERR_CHECKING_TID = MESSAGE_SET.getMessage("ERR_CHECKING_TID");

	/** The request going to SAP couldn't be converted to XML */
	public static final Message WRN_CONVERT = MESSAGE_SET.getMessage("WRN_CONVERT");

	/** Target mappings not loaded */
	public static final Message WRN_MAPPINGS_NOT_LOADED = MESSAGE_SET.getMessage("WRN_MAPPINGS_NOT_LOADED");

	/** Number of IDOC servers not properly specified in the processor configuration. */
	public static final Message WRN_NR_OF_SERVERS_NOT_SPECIFIED = MESSAGE_SET.getMessage("WRN_NR_OF_SERVERS_NOT_SPECIFIED");

	/** Error executing request: {0} */
	public static final Message ERROR_EXECUTING_REQUEST = MESSAGE_SET.getMessage("ERROR_EXECUTING_REQUEST");

	/** Error closing connector */
	public static final Message ERROR_CLOSING_CONNECTOR = MESSAGE_SET.getMessage("ERROR_CLOSING_CONNECTOR");

	/** Error dispatching idoc */
	public static final Message ERROR_DISPATCHING_IDOC = MESSAGE_SET.getMessage("ErrorDispatchingIdoc");

	/** Error loading xml: {0} */
	public static final Message ERROR_LOADING_XML = MESSAGE_SET.getMessage("ErrorLoadingXml");

	/** Wrn no usermapping found for user {0} */
	public static final Message WRN_NO_USERMAPPING_FOUND_FOR_USER = MESSAGE_SET.getMessage("WrnNoUsermappingFoundForUser");


}